name: check
on: [push]

jobs:
  find-integration-tests:
    runs-on: ubuntu-latest

    outputs:
      tests: ${{ steps.tests.outputs.tests }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Find tests
        id: tests
        run: tests=$(find integration_test -type f -name '*.sh' -printf '%p\n' | jq -R -s -c 'split("\n")[:-1]') && echo "tests=$tests" >> "$GITHUB_OUTPUT"

  integration-test:
    runs-on: ubuntu-latest
    needs: find-integration-tests
    strategy:
      matrix:
        test: ${{ fromJSON(needs.find-integration-tests.outputs.tests) }}
    name: Integration Tests
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Run test ${{ matrix.test }}
        uses: ./
        with:
          test-to-run: ${{ matrix.test }}

  format:
    runs-on: ubuntu-latest
    container:
      image: rust:latest
    name: cargo fmt
      - name: Checkout
        uses: actions/checkout@v5
      - name: cargo fmt
        run: cargo fmt --check

